<?php
namespace app\common\model;
class Newsclass extends \think\Model
{
	public $parent_list = array(
		1=>array(10,11,12,13),
		2=>array(14,15,16,17,30),
		3=>array(18,19,20,21,22,23),
		4=>array(24,25),
		5=>array(26,27,28),
	);
	public $class_list = array(
		array(
		'title'=>'栏目',
		'spread'=>true,
		'children'=>array(
			array(
				'id'=>1,
				'title'=>'药博会概况',
				'spread'=>true,
				'children'=>array(
					array(
						'id'=>10,
						'title'=>'健康中国',
						'spread'=>true,
					 ),
					array(
						'id'=>11,
						'title'=>'康养项目',
						'spread'=>true,
					 ),
					array(
						'id'=>12,
						'title'=>'往届回顾',
						'spread'=>true,
					 ),
					array(
						'id'=>13,
						'title'=>'政策法规',
						'spread'=>true,
					 ),
				),
			),
			array(
				'id'=>2,
				'title'=>'特色陇药',
				'spread'=>true,
				'children'=>array(
						array(
								'id'=>14,
								'title'=>'行业标准',
								'spread'=>true,
						),
						array(
								'id'=>15,
								'title'=>'陇药品牌',
								'spread'=>true,
						),
						array(
								'id'=>16,
								'title'=>'特色品种',
								'spread'=>true,
						),
						array(
								'id'=>17,
								'title'=>'陇药资讯',
								'spread'=>true,
						),
						array(
								'id'=>30,
								'title'=>'医药融合',
								'spread'=>true,
						),
				),
			),
			array(
				'id'=>3,
				'title'=>'药博会专区',
				'spread'=>true,
				'children'=>array(
						array(
								'id'=>18,
								'title'=>'直播药博会',
								'spread'=>true,
						),
						array(
								'id'=>19,
								'title'=>'人物专访',
								'spread'=>true,
						),
						array(
								'id'=>20,
								'title'=>'活动专场',
								'spread'=>true,
						),
						array(
								'id'=>21,
								'title'=>'招商引资',
								'spread'=>true,
						),
						array(
								'id'=>22,
								'title'=>'项目概况',
								'spread'=>true,
						),
						array(
								'id'=>23,
								'title'=>'沙盘展示',
								'spread'=>true,
						),
				),
			),
			array(
				'id'=>4,
				'title'=>'展览专区',
				'spread'=>true,
				'children'=>array(
						array(
								'id'=>24,
								'title'=>'市州概况',
								'spread'=>true,
						),
						array(
								'id'=>25,
								'title'=>'知名药企',
								'spread'=>true,
						),
				),
			),
			array(
				'id'=>5,
				'title'=>'新闻媒体',
				'spread'=>true,
				'children'=>array(
						array(
								'id'=>26,
								'title'=>'新闻资讯',
								'spread'=>true,
						),
						array(
								'id'=>27,
								'title'=>'现场报道',
								'spread'=>true,
						),
						array(
								'id'=>28,
								'title'=>'图文直播',
								'spread'=>true,
						),
				),
			),
		),
		)
	);
	public $recommend_list = array(
			array(
					'id'=>1,
					'title'=>'头条',
					'spread'=>true,
			),
			array(
					'id'=>2,
					'title'=>'轮播',
					'spread'=>true,
			),
			array(
					'id'=>3,
					'title'=>'要闻',
					'spread'=>true,
			),
			array(
					'id'=>4,
					'title'=>'药博会概况',
					'spread'=>true,
			),
			array(
					'id'=>5,
					'title'=>'特色陇药',
					'spread'=>true,
			),
			array(
					'id'=>6,
					'title'=>'药博会专区',
					'spread'=>true,
			),
			array(
					'id'=>7,
					'title'=>'健康中国',
					'spread'=>true,
			),
			array(
					'id'=>8,
					'title'=>'康养项目',
					'spread'=>true,
			),
	);
}
